import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { MapContainer, TileLayer, CircleMarker, Popup, useMap } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import {
  AlertTriangle, BarChart3, Bell, ChevronDown, ClipboardList, Crosshair, FileText, Flame,
  Hospital, LayoutDashboard, LifeBuoy, Map as MapIcon, Menu, Minus, Navigation, Plus,
  Radio, RefreshCw, Search, Shield, Siren, TentTree, Users, X, Zap
} from 'lucide-react';
import { supabase, type Alert, type Incident, type IncidentSeverity, type IncidentStatus, type IncidentType, type Resource, type ResourceStatus, type ResourceType } from '@/lib/supabase';
import { calculateHazardRisks, calculateRelocationPriorities, calculateVulnerability, summarizeHistory, type HazardRisk, type IntelligenceFactor } from '@/lib/intelligence';

type View = 'dashboard' | 'incidents' | 'resources' | 'alerts' | 'analytics' | 'intelligence';
type MapLayer = 'incidents' | 'resources';

const incidentLabels: Record<IncidentType, string> = { flood: 'Flood', fire: 'Fire', earthquake: 'Earthquake', hurricane: 'Hurricane', landslide: 'Landslide', chemical_spill: 'Chemical Spill', power_outage: 'Power Outage', medical: 'Medical Emergency', structural_collapse: 'Structural Collapse', other: 'Other' };
const severityColors: Record<IncidentSeverity, string> = { low: '#3b82f6', medium: '#f59e0b', high: '#f97316', critical: '#ef4444' };
const resourceLabels: Record<ResourceType, string> = { shelter: 'Shelter', hospital: 'Hospital', supply_depot: 'Supply Depot', rescue_team: 'Rescue Team', fire_station: 'Fire Station', police_station: 'Police Station', water_source: 'Water Source', helipad: 'Helipad' };
const statusLabels: Record<IncidentStatus, string> = { active: 'Active', contained: 'Contained', resolved: 'Resolved' };

function MapZoomControls() {
  const map = useMap();
  return <div className="map-controls"><button onClick={() => map.zoomIn()} aria-label="Zoom in"><Plus size={18} /></button><button onClick={() => map.zoomOut()} aria-label="Zoom out"><Minus size={18} /></button><button onClick={() => map.locate()} aria-label="Find my location"><Crosshair size={18} /></button></div>;
}

function App() {
  const [view, setView] = useState<View>('dashboard');
  const [incidents, setIncidents] = useState<Incident[]>([]);
  const [resources, setResources] = useState<Resource[]>([]);
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [selectedIncident, setSelectedIncident] = useState<Incident | null>(null);
  const [showReport, setShowReport] = useState(false);
  const [showResource, setShowResource] = useState(false);
  const [mapLayer, setMapLayer] = useState<MapLayer>('incidents');
  const [search, setSearch] = useState('');
  const [incidentFilter, setIncidentFilter] = useState<IncidentSeverity | 'all'>('all');
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState('');

  const loadData = async () => {
    setLoading(true);
    const [incidentResult, resourceResult, alertResult] = await Promise.all([
      supabase.from('incidents').select('*').order('created_at', { ascending: false }),
      supabase.from('resources').select('*').order('name'),
      supabase.from('alerts').select('*').eq('is_active', true).order('created_at', { ascending: false }),
    ]);
    if (!incidentResult.error) setIncidents((incidentResult.data ?? []) as Incident[]);
    if (!resourceResult.error) setResources((resourceResult.data ?? []) as Resource[]);
    if (!alertResult.error) setAlerts((alertResult.data ?? []) as Alert[]);
    setLoading(false);
  };

  useEffect(() => { void loadData(); }, []);

  const activeIncidents = incidents.filter((incident) => incident.status === 'active');
  const criticalIncidents = incidents.filter((incident) => incident.severity === 'critical' && incident.status !== 'resolved');
  const peopleAffected = incidents.reduce((sum, incident) => sum + (incident.affected_people || 0), 0);
  const availableResources = resources.filter((resource) => resource.status === 'available').length;
  const hazardRisks = useMemo(() => calculateHazardRisks(incidents), [incidents]);
  const vulnerabilities = useMemo(() => hazardRisks.map((risk) => calculateVulnerability(risk, resources)), [hazardRisks, resources]);
  const history = useMemo(() => summarizeHistory(incidents), [incidents]);
  const relocationPriorities = useMemo(() => calculateRelocationPriorities(hazardRisks, vulnerabilities, resources), [hazardRisks, vulnerabilities, resources]);
  const filteredIncidents = useMemo(() => incidents.filter((incident) => {
    const matchesSearch = `${incident.title} ${incident.location_name ?? ''} ${incidentLabels[incident.type]}`.toLowerCase().includes(search.toLowerCase());
    return matchesSearch && (incidentFilter === 'all' || incident.severity === incidentFilter);
  }), [incidents, search, incidentFilter]);

  const notify = (text: string) => { setMessage(text); window.setTimeout(() => setMessage(''), 3500); };

  const handleReport = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const { error } = await supabase.from('incidents').insert({ title: String(form.get('title')), description: String(form.get('description') || ''), type: String(form.get('type')) as IncidentType, severity: String(form.get('severity')) as IncidentSeverity, status: 'active', latitude: Number(form.get('latitude')), longitude: Number(form.get('longitude')), location_name: String(form.get('location_name') || ''), affected_people: Number(form.get('affected_people') || 0), reported_by: String(form.get('reported_by') || ''), contact_phone: String(form.get('contact_phone') || '') });
    if (error) { notify('Unable to submit the incident. Please check the details.'); return; }
    setShowReport(false); notify('Incident reported successfully.'); await loadData();
  };

  const handleResource = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const { error } = await supabase.from('resources').insert({ name: String(form.get('name')), type: String(form.get('type')) as ResourceType, status: String(form.get('status')) as ResourceStatus, latitude: Number(form.get('latitude')), longitude: Number(form.get('longitude')), address: String(form.get('address') || ''), capacity: Number(form.get('capacity') || 0), occupancy: Number(form.get('occupancy') || 0), contact_name: String(form.get('contact_name') || ''), contact_phone: String(form.get('contact_phone') || '') });
    if (error) { notify('Unable to add the resource. Please check the details.'); return; }
    setShowResource(false); notify('Resource added successfully.'); await loadData();
  };

  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark"><Shield size={23} /></div><div><strong>RESQ<span>GRID</span></strong><small>Emergency Operations</small></div></div>
      <div className="operation-status"><span className="status-dot" /> <span>Operations active</span><b>Live</b></div>
      <nav><p className="nav-label">COMMAND CENTER</p><NavItem icon={<LayoutDashboard size={18} />} label="Dashboard" active={view === 'dashboard'} onClick={() => setView('dashboard')} /><NavItem icon={<MapIcon size={18} />} label="Incident Map" active={view === 'incidents'} onClick={() => setView('incidents')} badge={activeIncidents.length} /><NavItem icon={<LifeBuoy size={18} />} label="Resources" active={view === 'resources'} onClick={() => setView('resources')} /><NavItem icon={<Bell size={18} />} label="Alerts" active={view === 'alerts'} onClick={() => setView('alerts')} badge={alerts.length} /><NavItem icon={<BarChart3 size={18} />} label="Analytics" active={view === 'analytics'} onClick={() => setView('analytics')} /><NavItem icon={<Shield size={18} />} label="Risk intelligence" active={view === 'intelligence'} onClick={() => setView('intelligence')} badge={hazardRisks.filter((risk) => risk.band === 'red').length} /><p className="nav-label second">OPERATIONS</p><NavItem icon={<FileText size={18} />} label="Field Reports" /><NavItem icon={<Users size={18} />} label="Response Teams" /><NavItem icon={<Radio size={18} />} label="Communications" /></nav>
      <div className="sidebar-footer"><div className="operator-avatar">OC</div><div><strong>Operations Center</strong><small>City Emergency Management</small></div><ChevronDown size={15} /></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><div className="mobile-brand"><Shield size={20} /> RESQGRID</div><div className="breadcrumbs"><span>Operations</span><b>/</b><strong>{view === 'dashboard' ? 'Dashboard' : view[0].toUpperCase() + view.slice(1)}</strong></div><div className="top-actions"><span className="last-updated"><RefreshCw size={14} /> Updated just now</span><button className="icon-button" onClick={() => void loadData()}><RefreshCw size={17} /></button><button className="icon-button alert-button" onClick={() => setView('alerts')}><Bell size={18} /><i>{alerts.length}</i></button><button className="menu-button"><Menu size={21} /></button></div></header>
      {message && <div className="toast"><span className="status-dot" />{message}</div>}
      <div className="page-content">
        <div className="page-heading"><div><p className="eyebrow">MONDAY, 24 AUGUST 2026 <span className="live-pill">LIVE</span></p><h1>{view === 'dashboard' ? 'Good morning, Operator' : view === 'incidents' ? 'Incident map' : view === 'resources' ? 'Emergency resources' : view === 'alerts' ? 'Active alerts' : 'Operations analytics'}</h1><p className="heading-sub">{view === 'dashboard' ? 'Here is your operational overview for today.' : 'Monitor and coordinate the regional emergency response.'}</p></div><div className="heading-actions"><button className="outline-button" onClick={() => setShowResource(true)}><LifeBuoy size={16} /> Add resource</button><button className="primary-button" onClick={() => setShowReport(true)}><Siren size={16} /> Report incident</button></div></div>
        {view === 'dashboard' && <Dashboard incidents={incidents} resources={resources} alerts={alerts} activeIncidents={activeIncidents} criticalIncidents={criticalIncidents} peopleAffected={peopleAffected} availableResources={availableResources} onMap={() => setView('incidents')} onSelect={setSelectedIncident} />}
        {view === 'incidents' && <IncidentMap incidents={filteredIncidents} resources={resources} mapLayer={mapLayer} setMapLayer={setMapLayer} onSelect={setSelectedIncident} search={search} setSearch={setSearch} incidentFilter={incidentFilter} setIncidentFilter={setIncidentFilter} />}
        {view === 'resources' && <ResourceView resources={resources} search={search} setSearch={setSearch} onAdd={() => setShowResource(true)} />}
        {view === 'alerts' && <AlertView alerts={alerts} />}
        {view === 'analytics' && <Analytics incidents={incidents} resources={resources} />}
        {view === 'intelligence' && <IntelligenceView risks={hazardRisks} vulnerabilities={vulnerabilities} history={history} relocationPriorities={relocationPriorities} />}
      </div>
    </main>
    {selectedIncident && <IncidentModal incident={selectedIncident} onClose={() => setSelectedIncident(null)} />}
    {showReport && <ReportModal onClose={() => setShowReport(false)} onSubmit={handleReport} />}
    {showResource && <ResourceModal onClose={() => setShowResource(false)} onSubmit={handleResource} />}
  </div>;
}

function NavItem({ icon, label, active = false, badge, onClick = () => {} }: { icon: React.ReactNode; label: string; active?: boolean; badge?: number; onClick?: () => void }) { return <button className={`nav-item ${active ? 'active' : ''}`} onClick={onClick}>{icon}<span>{label}</span>{badge !== undefined && badge > 0 && <em>{badge}</em>}</button>; }

function Dashboard({ incidents, resources, alerts, activeIncidents, criticalIncidents, peopleAffected, availableResources, onMap, onSelect }: { incidents: Incident[]; resources: Resource[]; alerts: Alert[]; activeIncidents: Incident[]; criticalIncidents: Incident[]; peopleAffected: number; availableResources: number; onMap: () => void; onSelect: (incident: Incident) => void }) { return <>
  <div className="stat-grid"><Stat icon={<Siren />} label="Active incidents" value={activeIncidents.length} trend="+3" trendText="vs. yesterday" tone="red" /><Stat icon={<AlertTriangle />} label="Critical situations" value={criticalIncidents.length} trend="+1" trendText="vs. yesterday" tone="amber" /><Stat icon={<Users />} label="People affected" value={peopleAffected.toLocaleString()} trend="+12%" trendText="vs. last update" tone="blue" /><Stat icon={<LifeBuoy />} label="Resources available" value={`${availableResources}/${resources.length}`} trend="82%" trendText="readiness rate" tone="green" /></div>
  <div className="dashboard-grid"><section className="panel map-panel"><PanelHeader title="Live incident map" subtitle="Regional overview" action={<button className="text-button" onClick={onMap}>Open full map <Navigation size={14} /></button>} /><div className="mini-map"><MapContainer center={[38, -96]} zoom={3} zoomControl={false} attributionControl={false} scrollWheelZoom={false}><TileLayer url="https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png" /><MapZoomControls />{incidents.filter((i) => i.status !== 'resolved').map((incident) => <CircleMarker key={incident.id} center={[incident.latitude, incident.longitude]} radius={incident.severity === 'critical' ? 10 : 7} pathOptions={{ color: severityColors[incident.severity], fillColor: severityColors[incident.severity], fillOpacity: .85, weight: 2 }} eventHandlers={{ click: () => onSelect(incident) }} />)}</MapContainer><div className="map-overlay-label"><span className="pulse" /> Live data</div><div className="map-legend"><span><i className="legend-dot critical" /> Critical</span><span><i className="legend-dot high" /> High</span><span><i className="legend-dot medium" /> Medium</span></div></div></section>
  <section className="panel alert-panel"><PanelHeader title="Priority alerts" subtitle={`${alerts.length} active notifications`} action={<button className="text-button">View all <Navigation size={14} /></button>} />{alerts.slice(0, 4).map((alert) => <div className={`alert-row ${alert.severity}`} key={alert.id}><div className="alert-icon"><AlertTriangle size={17} /></div><div><strong>{alert.title}</strong><p>{alert.area}</p><small>{timeAgo(alert.created_at)}</small></div></div>)}</section>
  </div>
  <section className="panel incidents-panel"><PanelHeader title="Recent incidents" subtitle="Latest reports from the field" action={<button className="text-button" onClick={onMap}>View all incidents <Navigation size={14} /></button>} /><IncidentTable incidents={incidents.slice(0, 5)} onSelect={onSelect} /></section>
</>; }

function Stat({ icon, label, value, trend, trendText, tone }: { icon: React.ReactNode; label: string; value: string | number; trend: string; trendText: string; tone: string }) { return <div className="stat-card"><div className={`stat-icon ${tone}`}>{icon}</div><div className="stat-info"><span>{label}</span><strong>{value}</strong><small><b className={tone === 'red' || tone === 'amber' ? 'up' : 'down'}>{trend}</b> {trendText}</small></div></div>; }
function PanelHeader({ title, subtitle, action }: { title: string; subtitle: string; action?: React.ReactNode }) { return <div className="panel-header"><div><h2>{title}</h2><p>{subtitle}</p></div>{action}</div>; }
function IncidentTable({ incidents, onSelect }: { incidents: Incident[]; onSelect: (incident: Incident) => void }) { return <div className="table-wrap"><table><thead><tr><th>Incident</th><th>Type</th><th>Severity</th><th>Status</th><th>Reported</th><th></th></tr></thead><tbody>{incidents.map((incident) => <tr key={incident.id} onClick={() => onSelect(incident)}><td><div className="incident-cell"><span className="row-icon" style={{ background: `${severityColors[incident.severity]}18`, color: severityColors[incident.severity] }}><IncidentIcon type={incident.type} /></span><div><strong>{incident.title}</strong><small>{incident.location_name}</small></div></div></td><td>{incidentLabels[incident.type]}</td><td><span className={`severity ${incident.severity}`}><i />{incident.severity}</span></td><td><span className={`status ${incident.status}`}>{statusLabels[incident.status]}</span></td><td>{timeAgo(incident.created_at)}</td><td><button className="row-more">•••</button></td></tr>)}</tbody></table></div>; }
function IncidentIcon({ type }: { type: IncidentType }) { if (type === 'fire') return <Flame size={17} />; if (type === 'flood') return <span className="text-icon">≈</span>; if (type === 'medical') return <Hospital size={17} />; if (type === 'power_outage') return <Zap size={17} />; return <AlertTriangle size={17} />; }

function IncidentMap({ incidents, resources, mapLayer, setMapLayer, onSelect, search, setSearch, incidentFilter, setIncidentFilter }: { incidents: Incident[]; resources: Resource[]; mapLayer: MapLayer; setMapLayer: (layer: MapLayer) => void; onSelect: (incident: Incident) => void; search: string; setSearch: (value: string) => void; incidentFilter: IncidentSeverity | 'all'; setIncidentFilter: (value: IncidentSeverity | 'all') => void }) { return <section className="panel full-map-panel"><div className="map-toolbar"><div className="search-box"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search incidents or locations" /></div><select value={incidentFilter} onChange={(event) => setIncidentFilter(event.target.value as IncidentSeverity | 'all')}><option value="all">All severities</option><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select><div className="layer-toggle"><button className={mapLayer === 'incidents' ? 'selected' : ''} onClick={() => setMapLayer('incidents')}><Siren size={15} /> Incidents</button><button className={mapLayer === 'resources' ? 'selected' : ''} onClick={() => setMapLayer('resources')}><LifeBuoy size={15} /> Resources</button></div></div><div className="large-map"><MapContainer center={[38, -96]} zoom={3} zoomControl={false} attributionControl={false}><TileLayer url="https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png" /><MapZoomControls />{mapLayer === 'incidents' ? incidents.map((incident) => <CircleMarker key={incident.id} center={[incident.latitude, incident.longitude]} radius={incident.severity === 'critical' ? 11 : 8} pathOptions={{ color: severityColors[incident.severity], fillColor: severityColors[incident.severity], fillOpacity: .85, weight: 2 }} eventHandlers={{ click: () => onSelect(incident) }}><Popup><strong>{incident.title}</strong><br />{incident.location_name}<br /><span className={`severity ${incident.severity}`}>{incident.severity}</span></Popup></CircleMarker>) : resources.map((resource) => <CircleMarker key={resource.id} center={[resource.latitude, resource.longitude]} radius={7} pathOptions={{ color: '#2dd4bf', fillColor: '#2dd4bf', fillOpacity: .8 }}><Popup><strong>{resource.name}</strong><br />{resourceLabels[resource.type]} · {resource.status}</Popup></CircleMarker>)}</MapContainer><div className="map-key"><span><i className="legend-dot critical" /> Critical</span><span><i className="legend-dot high" /> High</span><span><i className="legend-dot medium" /> Medium</span><span><i className="legend-dot low" /> Low</span><span><i className="legend-dot resource" /> Resources</span></div></div></section>; }

function ResourceView({ resources, search, setSearch, onAdd }: { resources: Resource[]; search: string; setSearch: (value: string) => void; onAdd: () => void }) { const filtered = resources.filter((resource) => `${resource.name} ${resource.address ?? ''} ${resourceLabels[resource.type]}`.toLowerCase().includes(search.toLowerCase())); return <section className="panel resource-panel"><div className="resource-toolbar"><div className="search-box"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search resources" /></div><button className="outline-button" onClick={onAdd}><Plus size={16} /> Add resource</button></div><div className="resource-grid">{filtered.map((resource) => <div className="resource-card" key={resource.id}><div className="resource-card-top"><div className="resource-icon"><ResourceIcon type={resource.type} /></div><span className={`resource-status ${resource.status}`}>{resource.status}</span></div><h3>{resource.name}</h3><p>{resourceLabels[resource.type]} · {resource.address}</p><div className="capacity"><div><span>Capacity</span><strong>{resource.occupancy} <small>/ {resource.capacity}</small></strong></div><div className="capacity-bar"><i style={{ width: `${Math.min(100, resource.capacity ? (resource.occupancy / resource.capacity) * 100 : 0)}%` }} /></div></div><div className="resource-contact"><span>{resource.contact_name}</span><b>{resource.contact_phone}</b></div></div>)}</div></section>; }
function ResourceIcon({ type }: { type: ResourceType }) { if (type === 'shelter') return <TentTree size={21} />; if (type === 'hospital') return <Hospital size={21} />; if (type === 'fire_station') return <Flame size={21} />; if (type === 'rescue_team') return <Users size={21} />; return <LifeBuoy size={21} />; }
function AlertView({ alerts }: { alerts: Alert[] }) { return <section className="panel alert-list-panel"><PanelHeader title="Emergency broadcast center" subtitle="Active alerts currently visible to operators" action={<span className="live-pill">{alerts.length} ACTIVE</span>} />{alerts.map((alert) => <article className={`full-alert ${alert.severity}`} key={alert.id}><div className="full-alert-icon"><AlertTriangle size={21} /></div><div><div className="alert-meta"><span>{alert.severity}</span><small>{timeAgo(alert.created_at)}</small></div><h3>{alert.title}</h3><p>{alert.message}</p><strong>{alert.area}</strong></div></article>)}</section>; }
function IntelligenceView({ risks, vulnerabilities, history, relocationPriorities }: { risks: HazardRisk[]; vulnerabilities: ReturnType<typeof calculateVulnerability>[]; history: ReturnType<typeof summarizeHistory>; relocationPriorities: ReturnType<typeof calculateRelocationPriorities> }) { return <div className="intelligence-workspace">
  <div className="intelligence-intro"><div><p className="eyebrow">DECISION SUPPORT / MODEL OUTPUT</p><h2>Risk intelligence</h2><p>Every score is calculated from the live incident and resource dataset. Select a Red Zone to inspect the factors behind its ranking.</p></div><div className="model-badge"><Shield size={17} /><span><strong>Transparent model</strong><small>Updated from current records</small></span></div></div>
  <div className="intelligence-grid"><section className="panel red-zone-panel"><PanelHeader title="Red Zone identification" subtitle={`${risks.filter((risk) => risk.band === 'red').length} areas meet the 70-point escalation threshold`} action={<span className="threshold-pill">RED ZONE ≥ 70</span>} />{risks.length === 0 ? <EmptyState text="No active incidents to score." /> : risks.map((risk) => <RiskRow key={risk.area} risk={risk} />)}</section><section className="panel vulnerability-panel"><PanelHeader title="Vulnerability scoring" subtitle="Exposure, capacity gap, and readiness" />{vulnerabilities.map((item) => <div className="vulnerability-row" key={item.area}><div><strong>{item.area}</strong><small>{item.band} vulnerability</small></div><strong className={`score-number ${item.band}`}>{item.score}</strong><div className="score-track"><i className={item.band} style={{ width: `${item.score}%` }} /></div></div>)}</section></div>
  <div className="intelligence-grid lower"><section className="panel relocation-panel"><PanelHeader title="Relocation priority" subtitle="Recommended order based on risk × vulnerability" />{relocationPriorities.map((priority, index) => <div className="relocation-row" key={priority.area}><div className="priority-rank">0{index + 1}</div><div className="relocation-main"><div><strong>{priority.area}</strong><span className={`priority-tag ${priority.priority}`}>{priority.priority}</span></div><p>{priority.reason}</p><small>{priority.affectedPeople.toLocaleString()} exposed · {priority.availableCapacity.toLocaleString()} nearby places available</small></div><div className="priority-score"><strong>{priority.score}</strong><small>/ 100</small></div><details className="factor-details"><summary>Factors</summary><div className="factor-popover">{priority.factors.map((factor) => <Factor key={factor.label} factor={factor} />)}</div></details></div>)}</section><section className="panel history-panel"><PanelHeader title="Historical disaster analysis" subtitle="Patterns from all records in the dataset" /><div className="history-stats"><div><strong>{history.total}</strong><span>Total events</span></div><div><strong>{history.resolved}</strong><span>Resolved</span></div><div><strong>{history.averageAffected.toLocaleString()}</strong><span>Avg. affected</span></div></div><div className="history-section"><h3>Hazard mix</h3>{history.byType.map((item) => <div className="history-bar" key={item.label}><span>{item.label}</span><div><i style={{ width: `${item.share}%` }} /></div><b>{item.count}</b></div>)}</div><div className="history-section"><h3>Severity distribution</h3>{history.bySeverity.map((item) => <span className={`distribution-pill ${item.label.toLowerCase()}`} key={item.label}>{item.label} {item.share}%</span>)}</div></section></div>
</div>; }
function RiskRow({ risk }: { risk: HazardRisk }) { return <details className={`risk-row ${risk.band}`} open={risk.band === 'red'}><summary><div className="risk-marker"><span /></div><div className="risk-name"><strong>{risk.area}</strong><small>{risk.hazardTypes.join(' + ')} · {risk.affectedPeople.toLocaleString()} exposed</small></div><span className={`risk-band ${risk.band}`}>{risk.band === 'red' ? 'RED ZONE' : risk.band}</span><strong className="risk-score">{risk.score}<small>/100</small></strong><ChevronDown size={16} /></summary><div className="factor-list">{risk.factors.map((factor) => <Factor key={factor.label} factor={factor} />)}</div></details>; }
function Factor({ factor }: { factor: IntelligenceFactor }) { return <div className="factor"><div><strong>{factor.label}</strong><small>{factor.explanation}</small></div><b>+{factor.contribution}</b></div>; }
function EmptyState({ text }: { text: string }) { return <div className="empty-state">{text}</div>; }

function Analytics({ incidents, resources }: { incidents: Incident[]; resources: Resource[] }) { const counts = (Object.keys(incidentLabels) as IncidentType[]).map((type) => ({ type, count: incidents.filter((incident) => incident.type === type).length })).filter((item) => item.count); const max = Math.max(...counts.map((item) => item.count), 1); return <div className="analytics-grid"><section className="panel chart-panel"><PanelHeader title="Incidents by type" subtitle="All reported incidents" />{counts.map((item) => <div className="bar-row" key={item.type}><span>{incidentLabels[item.type]}</span><div><i style={{ width: `${item.count / max * 100}%` }} /></div><b>{item.count}</b></div>)}</section><section className="panel chart-panel"><PanelHeader title="Resource readiness" subtitle="Current operational capacity" />{resources.map((resource) => <div className="bar-row" key={resource.id}><span>{resource.name}</span><div><i className={resource.status} style={{ width: `${resource.capacity ? Math.min(100, resource.occupancy / resource.capacity * 100) : 0}%` }} /></div><b>{resource.status}</b></div>)}</section></div>; }

function IncidentModal({ incident, onClose }: { incident: Incident; onClose: () => void }) { return <div className="modal-backdrop" onClick={onClose}><div className="modal" onClick={(event) => event.stopPropagation()}><ModalHeader title="Incident details" onClose={onClose} /><div className="modal-incident-head"><span className="row-icon large" style={{ background: `${severityColors[incident.severity]}18`, color: severityColors[incident.severity] }}><IncidentIcon type={incident.type} /></span><div><p className="eyebrow">{incidentLabels[incident.type]}</p><h2>{incident.title}</h2><span className={`severity ${incident.severity}`}><i />{incident.severity} priority</span></div></div><div className="detail-grid"><div><span>Location</span><strong>{incident.location_name}</strong></div><div><span>People affected</span><strong>{incident.affected_people.toLocaleString()}</strong></div><div><span>Reported by</span><strong>{incident.reported_by || 'Operations Center'}</strong></div><div><span>Contact</span><strong>{incident.contact_phone || 'Not provided'}</strong></div></div><div className="detail-description"><span>Description</span><p>{incident.description || 'No additional description provided.'}</p></div><button className="primary-button full-button" onClick={onClose}>Acknowledge incident</button></div></div>; }
function ReportModal({ onClose, onSubmit }: { onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="modal-backdrop" onClick={onClose}><form className="modal form-modal" onClick={(event) => event.stopPropagation()} onSubmit={onSubmit}><ModalHeader title="Report an incident" onClose={onClose} /><div className="form-grid"><label className="wide">Incident title<input name="title" required placeholder="e.g. Flooding on Riverside Drive" /></label><label>Type<select name="type" defaultValue="flood">{(Object.keys(incidentLabels) as IncidentType[]).map((type) => <option key={type} value={type}>{incidentLabels[type]}</option>)}</select></label><label>Severity<select name="severity" defaultValue="medium"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label><label className="wide">Location name<input name="location_name" required placeholder="Area, street, or landmark" /></label><label>Latitude<input name="latitude" type="number" step="any" required placeholder="40.7128" /></label><label>Longitude<input name="longitude" type="number" step="any" required placeholder="-74.0060" /></label><label>Affected people<input name="affected_people" type="number" min="0" defaultValue="0" /></label><label>Reported by<input name="reported_by" placeholder="Your name" /></label><label className="wide">Contact phone<input name="contact_phone" placeholder="555-0100" /></label><label className="wide">Description<textarea name="description" rows={3} placeholder="Describe what is happening..." /></label></div><button type="submit" className="primary-button full-button">Submit incident report</button></form></div>; }
function ResourceModal({ onClose, onSubmit }: { onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="modal-backdrop" onClick={onClose}><form className="modal form-modal" onClick={(event) => event.stopPropagation()} onSubmit={onSubmit}><ModalHeader title="Add emergency resource" onClose={onClose} /><div className="form-grid"><label className="wide">Resource name<input name="name" required placeholder="e.g. Central Emergency Shelter" /></label><label>Type<select name="type" defaultValue="shelter">{(Object.keys(resourceLabels) as ResourceType[]).map((type) => <option key={type} value={type}>{resourceLabels[type]}</option>)}</select></label><label>Status<select name="status" defaultValue="available"><option value="available">Available</option><option value="full">Full</option><option value="deployed">Deployed</option><option value="maintenance">Maintenance</option></select></label><label className="wide">Address<input name="address" placeholder="Street address" /></label><label>Latitude<input name="latitude" type="number" step="any" required placeholder="40.7128" /></label><label>Longitude<input name="longitude" type="number" step="any" required placeholder="-74.0060" /></label><label>Capacity<input name="capacity" type="number" min="0" defaultValue="0" /></label><label>Current occupancy<input name="occupancy" type="number" min="0" defaultValue="0" /></label><label>Contact name<input name="contact_name" placeholder="Contact person" /></label><label>Contact phone<input name="contact_phone" placeholder="555-0100" /></label></div><button type="submit" className="primary-button full-button">Add resource</button></form></div>; }
function ModalHeader({ title, onClose }: { title: string; onClose: () => void }) { return <div className="modal-header"><h2>{title}</h2><button onClick={onClose} aria-label="Close"><X size={20} /></button></div>; }
function timeAgo(date: string) { const diff = Math.max(1, Math.floor((Date.now() - new Date(date).getTime()) / 60000)); if (diff < 60) return `${diff} min ago`; if (diff < 1440) return `${Math.floor(diff / 60)} hr ago`; return `${Math.floor(diff / 1440)} days ago`; }

export default App;
